#!/usr/bin/env bash
args=(
    # Standard search paths for sysroot 
    -Wl,-rpath-link,$SYSROOT/usr/lib/aarch64-linux-gnu/
    -Wl,-rpath-link,$SYSROOT/lib/aarch64-linux-gnu/
    -Wl,-rpath-link,$SYSROOT/usr/local/lib/aarch64-linux-gnu/
    -Wl,-rpath-link,$SYSROOT/usr/local/cuda-10.2/targets/aarch64-linux/lib/
    -Wl,-rpath-link,$SYSROOT/opt/opencv-4.6.0/lib/
    
    # Some subdirectories are needed b/c these are in /usr/lib/aarch64-linux-gnu/
    # by symlinks (absolute) which don't work in the sysroot!
    # May need to add to these if adding libraries that work this way
    # Essentially, if it uses debian's update-alternatives thing, it's symlinked
    # TODO: Determine if there's a way to rewrite to relative symlinks
    #       when creating sysroot
    -Wl,-rpath-link,$SYSROOT/usr/lib/aarch64-linux-gnu/tegra/
    -Wl,-rpath-link,$SYSROOT/usr/lib/aarch64-linux-gnu/lapack/
    -Wl,-rpath-link,$SYSROOT/usr/lib/aarch64-linux-gnu/blas/

    # Sysroot must be AFTER these search paths!
    -Wl,--sysroot=$SYSROOT
)

# Invoke with arguments above and anything passed to this script
aarch64-linux-gnu-gcc "${args[@]}" "$@"